name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    branches:
    - '**'
    paths:
      - '.github/workflows/build.yml'
      - 'boards/**'
      - 'config/**'
      - 'snippets/**'
      - 'build.yaml'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'boards/**'
      - 'config/**'
      - 'snippets/**'
      - 'build.yaml'

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3.0
    with:
      # Node.js 24を強制するための環境変数を渡します
      extra_env: |
        FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true
